---
- name: Set up firewall on Ubuntu and CentOS
  hosts: control_node
  become: yes  # Run tasks with sudo
  tasks:

    - name: Install UFW on Ubuntu
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Set default incoming policy to deny on Ubuntu
      ansible.builtin.command: ufw default deny incoming
      when: ansible_os_family == 'Debian'

    - name: Set default outgoing policy to allow on Ubuntu
      ansible.builtin.command: ufw default allow outgoing
      when: ansible_os_family == 'Debian'

    - name: Allow SSH through UFW on Ubuntu
      ansible.builtin.command: ufw allow ssh
      when: ansible_os_family == 'Debian'

    - name: Enable UFW on Ubuntu
      ansible.builtin.command: ufw --force enable
      when: ansible_os_family == 'Debian'

    - name: Install Firewalld on CentOS
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start and enable Firewalld on CentOS
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Allow SSH through Firewalld on CentOS
      ansible.builtin.firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == 'RedHat'

    - name: Set default zone to deny other traffic (optional - for strict security)
      ansible.builtin.firewalld:
        port: 1-65535/tcp
        zone: public
        state: disabled
        immediate: yes
        permanent: yes
      when: ansible_os_family == 'RedHat'

